version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_and_release

jobs:
  "build_and_release":
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.9.1-browsers
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: critical
          command: npm run critical
      - run:
          name: minify
          command: npm run minify
      - run:
          name: install-firebase-tools
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - run:
          name: deploy-to-firebase
          environment:
            BRANCH: <<pipeline.git.branch>>
          command: |
            if [ "${BRANCH}" == "master" ]; then
              npm run travis-deploy
            else
              npm run travis-deploy-test
            fi
